### ISSUE TITLE
关于配图问题

### ISSUE THREAD

**Issue by qq40171204** [SumiMakito/hexo-theme-Journal#12]
使用featured_image: 以后首页不显示配图，文章页，能出现配图的框，却是空白的。

**Comment by kinglisky** [comment]
featured_image 图片的路径是相对路径还是？目前好像直接追加到当前页面的末尾？

![image](https://user-images.githubusercontent.com/15852576/56088722-36088700-5eb9-11e9-9e48-fa7ac8412168.png)

![image](https://user-images.githubusercontent.com/15852576/56088724-3ef95880-5eb9-11e9-98e9-46c2539af122.png)

![image](https://user-images.githubusercontent.com/15852576/56088733-53d5ec00-5eb9-11e9-818e-bd9a7fd3ccac.png)

**Comment by SumiMakito** [comment]
你好，这个 featured_image 需要使用相对于文章目录的路径，例如使用 `hexo new article_name` 新建文章的话，在 source/_post 下会有 article_name.md 与 article_name 文件夹生成，`featured_image` 只需要给出 article_name 下图片的名称即可。
