### ISSUE TITLE
希望featured_image可以自定义图片链接

### ISSUE THREAD

**Issue by chensu8** [SumiMakito/hexo-theme-Journal#15]
希望featured_image可以自定义图片链接

**Comment by wanmaoor** [comment]
featured_image 的图片该去哪个目录找啊?

**Comment by SumiMakito** [comment]
25a0dde29914c030a5b84d073917585c4e301fb8 加入了 Feature image 对 http:// 与 https:// 前缀的外部图片 URL 支持。

可以尝试 2.0.3
