### ISSUE TITLE
侧边栏[归档]标签默认生成

### ISSUE THREAD

**Issue by Vincentie** [SumiMakito/hexo-theme-Journal#16]
首先谢谢玛奇朵的主题~
然后是想问每次hexo clean & hexo g & hexo s以后，侧边栏都会在生成一个[Archive]或者[記事一覽]的默认标签，想请问一下这个如何自定义呢？（实在没有找到可以修改的地方）

![图片](https://user-images.githubusercontent.com/28601920/62060981-33c20280-b1f4-11e9-83df-aa84ca7bf976.png)
![图片](https://user-images.githubusercontent.com/28601920/62065670-776d3a00-b1fd-11e9-97c6-f065a5dd5199.png)

谢谢玛奇朵！

**Comment by Vincentie** [comment]
好的 我知道在哪里可以改了lol
在```layout\_include```路径下的```side_nav.ejs```和```single_column_head.ejs```改动就可以了，但是还是疑惑为什么会生成[記事一覽]lol

**Comment by SumiMakito** [comment]
抱歉之前比较忙很久都没有查看这个 Repo 下的 Issues，谢谢使用。

如果不需要 i18n 支持的话可以直接在 *side_nav.ejs* 和 *single_column_head.ejs* 中修改 Archives 的名称，不希望显示的话也可以直接删除。

在 7dc9a4d2edd331c9ff4454aa6162c75942f2914c 中我加了个可以在主题目录 _config.yml 设置是否显示 Archives 的参数，类似控制 RSS 的那个参数。

```yaml
archives: true
```
