### ISSUE TITLE
大佬能否移植到hugo上？

### ISSUE THREAD

**Issue by Newamber** [SumiMakito/hexo-theme-Journal#18]
真的是太喜欢这个主题了，然而我本身不是这个技术栈的，
自己没有那个能力复刻一个到hugo上 Ｔ Ｔ，虽然会增加大佬的工作量，但还是厚着脸皮问一下

**Comment by AmazingRise** [comment]
@Newamber 
你的愿望实现了 2333
我花了大概一周的时间移植这个主题,可以看一下哦~
https://github.com/AmazingRise/hugo-theme-diary

**Comment by newamber** [comment]
多谢大佬! 😄
