### ISSUE TITLE
请问这个主题在windows环境下能运行吗

### ISSUE THREAD

**Issue by fe405327114** [SumiMakito/hexo-theme-Journal#3]
这个目录打开一直报错。用其他的主题没问题。
ERROR ENOENT: no such file or directory, open 'E:\blog\node_modules\extended-ejs\E:\blog\themes\Journal\layout\skeleton.ejs'

**Comment by SumiMakito** [comment]
抱歉，可能是我的 `extended-ejs` 对 Windows 支持有问题，目前已经去掉了对这个渲染器的依赖。
可以尝试执行 `yarn remove hexo-renderer-extended-ejs` 然后 `yarn add hexo-renderer-ejs` 换回 EJS 模板渲染器，然后再运行博客。
多谢支持。
