### ISSUE TITLE
桌面版主页会显示很多的滚动条，应该是个 bug。

### ISSUE THREAD

**Issue by NekoApocalypse** [SumiMakito/hexo-theme-Journal#6]
路过，Chrome 68 和 FireFox Quantum 都会出现这个问题

左边 nav panel 和右边显示箭头的区域都有纵向和横向的 scroll bar。都是没有装饰过的那种样式，其中箭头区域的可以左右滚动其他都不能滚动。

看上去应该是 CSS 有问题。

**Comment by SumiMakito** [comment]
谢谢反馈，之前忙于学校的事情和其他项目一直没有搭理这个主题，我是前一段时间换了个鼠标才发现滚动条这个问题，修了一部分，不知道其他地方还会不会存在问题。
