### ISSUE TITLE
关于图标加载的报错

### ISSUE THREAD

**Issue by momodayzz** [SumiMakito/hexo-theme-Journal#9]
1. 用 Edge 和 Chrome 访问文章页时，会出现返回顶层按钮没有加载出来的情况。
2. 用 Edge 访问首页时，文章翻页按钮处会出现没有加载出来的情况。

谢谢朵朵！

**Comment by SumiMakito** [comment]
是指会出现图标名称而不是图标的问题嘛？我好像还没能成功复现，不知道问题有没有得到解决，如果还存在欢迎继续反馈哦〜
